heat_template_version: 2013-05-23

description: Deploy A Moodle (28) Environment

parameters:
  domain:
    type: string
    label: Domain
    default: cloudtrain.me

resources:
  password:
    type: OS::Heat::RandomString
    properties:
      length: 12
      sequence: lettersdigits

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: "%prefix%-moodle-keypair"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      save_private_key: True

  network:
    type: Rackspace::Cloud::Network
    properties:
      cidr: 192.168.2.0/24
      label:
        str_replace:
          template: "%prefix%-moodle-private"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }

  database:
    type: OS::Trove::Instance
    depends_on: [ password, network ]
    properties:
      name:
        str_replace:
          template: "%prefix%-moodle-database"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      flavor: 1GB Instance
      size: 5
      networks:
        - network: 00000000-0000-0000-0000-000000000000
        - network: 11111111-1111-1111-1111-111111111111
        - network: { get_resource: network }
      datastore_type: "mysql"
      datastore_version: "5.6"
      databases:
        - name: moodle
      users:
        - name: moodle
          password: { get_attr: [ password, value ] }
          databases:
            - moodle

  swift_signal_handle_app1:
    type: OS::Heat::SwiftSignalHandle

  cloud_config_app1:
    type: OS::Heat::CloudConfig
    depends_on: [ password, database, swift_signal_handle_app1 ]
    properties:
      cloud_config:
        output:
          all: '| tee -a /var/log/cloud-init-output.log'
        apt_upgrade: true
        packages:
          - tmux
          - htop
          - multitail
          - build-essential
          - software-properties-common
          - python-software-properties
          - curl
          - git-core
          - python-pip
          - python-apt
          - python-dev
        write_files:
          - path: /opt/cloud-training/inventory
            permissions: "0600"
            content:
              str_replace:
                template: |
                  [all:vars]
                  database_hostname=%database_hostname%
                  database_password=%database_password%
                  moodle_hostname=%moodle_hostname%
                  [local]
                  localhost    ansible_connection=local
                params:
                  "%database_hostname%": { get_attr: [ database, hostname ] }
                  "%database_password%": { get_attr: [ password, value ] }
                  "%moodle_hostname%":
                    str_replace:
                      template: "moodle.%prefix%.%domain%"
                      params:
                        "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
                        "%domain%": { get_param: domain }
          - path: /opt/cloud-training/runcmd-bash
            permissions: "0700"
            content:
              str_replace:
                template: |
                  #!/bin/bash
                  set -e
                  set -x
                  function exit_failure {
                    echo "$@"
                    %swift_signal_notify% --data-binary '{"status": "FAILURE", "reason": "'"$@"'"}'
                    exit 1
                  }
                  function exit_success {
                    %swift_signal_notify% --data-binary '{"status": "SUCCESS"}'
                  }
                  /usr/bin/pip install --upgrade pip || exit_failure "PIP Upgrade PIP Failure"
                  /usr/local/bin/pip install pip==1.5.6 || exit_failure "PIP Install PIP Failure"
                  /usr/local/bin/pip install ansible==1.6.5 || exit_failure "PIP Install Ansible Failure"
                  mkdir -p /opt/cloud-training
                  cd /opt/cloud-training
                  git clone https://github.com/cloud-training/moodle-heat-ansible.git || exit_failure "Git Clone Failure"
                  mv /opt/cloud-training/inventory /opt/cloud-training/moodle-heat-ansible/inventory
                  cd /opt/cloud-training/moodle-heat-ansible
                  ansible-playbook moodle-playbook.yml -vv || exit_failure "Ansible Playbook Run Failure"
                  exit_success
                params:
                  "%swift_signal_notify%": { get_attr: [ swift_signal_handle_app1, curl_cli ] }
        runcmd:
          - /opt/cloud-training/runcmd-bash

  server_app1:
    type: OS::Nova::Server
    depends_on: [ password, keypair, network, cloud_config_app1 ]
    properties:
      name:
        str_replace:
          template: "%prefix%-moodle-app1"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      flavor: 8 GB General Purpose v1
      image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - network: { get_resource: network }
      key_name: { get_resource: keypair }
      admin_pass: { get_attr: [ password, value ] }
      config_drive: True
      user_data_format: RAW
      user_data: { get_resource: cloud_config_app1 }

  dns:
    type: Rackspace::Cloud::DNS
    properties:
      name:
        str_replace:
          template: "%prefix%.%domain%"
          params:
            "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
            "%domain%": { get_param: domain }
      emailAddress: ipadmin@stabletransit.com
      records:
        - type: A
          data: { get_attr: [ server_app1, accessIPv4 ] }
          name:
            str_replace:
              template: "moodle.%prefix%.%domain%"
              params:
                "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
                "%domain%": { get_param: domain }

  swift_signal_app1:
    type: OS::Heat::SwiftSignal
    properties:
      handle: { get_resource: swift_signal_handle_app1 }
      count: 1
      timeout: 7200

outputs:
  password:
    description: Password
    value: { get_attr: [ password, value ] }
  public_key:
    description: Public Key
    value: { get_attr: [ keypair, public_key ] }
  private_key:
    description: Private Key
    value: { get_attr: [ keypair, private_key ] }
  url:
    description: Moodle URL
    value:
      str_replace:
        template: "http://moodle.%prefix%.%domain%/"
        params:
          "%prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
          "%domain%": { get_param: domain }
