---
# This playbook installs Moodle (28)

- name: Install Moodle (28)
  hosts: local
  tasks:
    - name: Install Packages
      apt: name={{ item }} state=present
      with_items:
        - apache2
        - mysql-client
        - php5
        - graphviz
        - aspell
        - php5-pspell
        - php5-curl
        - php5-gd
        - php5-intl
        - php5-mysql
        - php5-xmlrpc
        - php5-ldap
        - clamav
      register: install_packages

    - name: Restart Apache
      service: name=apache2 state=restarted
      when: install_packages.changed

    - name: Clone Moodle
      git: repo=git://git.moodle.org/moodle.git dest=/opt/moodle version=MOODLE_28_STABLE
