---
# This playbook installs Moodle (28)

- name: Install Moodle (28)
  hosts: local
  tasks:
    - name: Install Packages
      apt: name={{ item }} state=present
      with_items:
        - apache2
        - mysql-client
        - php5
