---
# This playbook installs Moodle (28)

- name: Install Moodle (28)
  hosts: local
  tasks:
    - name: Ping Nodes
      ping:

    - name: Debug Database Hostname
      debug: var=database_hostname

    - name: Debug Database Password
      debug: var=database_password
